name: 'Simple coverage'
description: 'Do simple coverage check'
author: 'SpreadMonitor'
inputs:
  line-coverage-threshold:
    required: false
    description: 'Threshold value for line coverage.'
  coverage-reports:
    required: false
    description: 'Absolute or relative paths to the coverage-final report JSON files.'
outputs:
  line-coverage:
    description: 'Line coverage percentage.'
runs:
  using: node16
  main: 'dist/index.js'
